FromDoppler/doppler-push-contact

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact.Test/Doppler.PushContact.Test.csproj
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Models/PushContactModel.cs
- Doppler.PushContact/Services/IPushContactService.cs
- Doppler.PushContact/Services/PushContactService.cs
- Doppler.PushContact/Startup.cs
Related to [DO-71](https://makingsense.atlassian.net/browse/DO-71)
> [DO-71] Create add a push contact endpoint

- Doppler.PushContact.Test/Doppler.PushContact.Test.csproj
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Doppler.PushContact.csproj
- Doppler.PushContact/Models/PushContactModel.cs
- Doppler.PushContact/Services/PushContactMongoContextSettings.cs
- Doppler.PushContact/Services/PushContactService.cs
- Doppler.PushContact/Startup.cs
- Doppler.PushContact/appsettings.json
Related to [DO-72](https://makingsense.atlassian.net/browse/DO-72)
---
>  [DO-72] Push contact storage implementation

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/IPushContactService.cs
- Doppler.PushContact/Services/PushContactFilter.cs
- Doppler.PushContact/Services/PushContactService.cs
Related to [DO-74](https://makingsense.atlassian.net/browse/DO-74)
> [DO-74] Create get push contacts endpoint

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
Related to [DO-77](https://makingsense.atlassian.net/browse/DO-77)
> [DO-77] Change add push contact endpoint route

- Doppler.PushContact/Services/PushContactService.cs
Related to [https://makingsense.atlassian.net/browse/DO-84](DO-84)
> [DO-84] Fix IAsyncCursor can only be enumerated once error

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/IPushContactService.cs
- Doppler.PushContact/Services/PushContactService.cs
Related to [DO-83](https://makingsense.atlassian.net/browse/DO-83)
> [DO-83] Add delete push contacts by device token endpoint

- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Services/PushContactMongoContextSettings.cs
- Doppler.PushContact/Services/PushContactService.cs
- Doppler.PushContact/Services/PushContactServiceExtensions.cs
- Doppler.PushContact/Startup.cs
- Doppler.PushContact/appsettings.json
Related to [DO-79](https://makingsense.atlassian.net/browse/DO-79)
> [DO-79] Split MongoDb connection string

- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Services/PushContactService.cs
Related to [DOM-86](https://makingsense.atlassian.net/browse/DOM-86)
> [DOM-86] Remove deleted push contacts from service Get method

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Models/PushContactModel.cs
- Doppler.PushContact/Services/PushContactService.cs
Related to [DOM-91](https://makingsense.atlassian.net/browse/DOM-91)
> [DOM-91] Add Email field to Push Contact contract

- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Services/PushContactService.cs
Related to [DOM-92](https://makingsense.atlassian.net/browse/DOM-92)
> Add null treatment in get push contacts

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Models/PushContactHistoryEvent.cs
- Doppler.PushContact/Services/IPushContactService.cs
- Doppler.PushContact/Services/PushContactService.cs
Related to [DOM-96](https://makingsense.atlassian.net/browse/DOM-96)
> [DOM-96] Add history events collection into push contact document

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/IPushContactService.cs
- Doppler.PushContact/Services/PushContactService.cs
Related to [DOM-101](https://makingsense.atlassian.net/browse/DOM-101) and [this](https://github.com/FromDoppler/doppler-push-contact/pull/25#discussion_r696063433) comment
> [DOM-101] Add new endpoint to update email push contact field

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/PushContactFilter.cs
- Doppler.PushContact/Services/PushContactService.cs
Related to [DOM-107](https://makingsense.atlassian.net/browse/DOM-107)
> [DOM-107] Add email push contact filter in GET method

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
This PR is a fix related to GET push contacts endpoint. In this PR I made the `domain` param required and change test implementation related to this param.
> Add domain required check in GET push contacts endpoint

- Doppler.PushContact.Test/Services/DeviceTokenValidatorTest.cs
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Doppler.PushContact.csproj
- Doppler.PushContact/Services/DeviceTokenValidator.cs
- Doppler.PushContact/Services/DeviceTokenValidatorSettings.cs
- Doppler.PushContact/Services/IDeviceTokenValidator.cs
- Doppler.PushContact/Services/PushContactService.cs
- Doppler.PushContact/Services/PushContactServiceExtensions.cs
- Doppler.PushContact/appsettings.json
~~🚧 Pending [doppler-push-api](https://github.com/FromDoppler/doppler-push-api) call to validate token~~
Related to [DOM-124](https://makingsense.atlassian.net/browse/DOM-124)
> [DOM-124] Add device token validation before create and edit push contacts

- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Services/PushContactDocumentProps.cs
- Doppler.PushContact/Services/PushContactService.cs
- Doppler.PushContact/Services/PushContactServiceExtensions.cs
Related to [DOM-126](https://makingsense.atlassian.net/browse/DOM-126)
> [DOM-126] Add device token unique index in push contacts collection

- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Services/PushContactService.cs
Related to [DOM-128](https://makingsense.atlassian.net/browse/DOM-128)
> [DOM-128] Allow null or empty email on create push contact

- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
This PR is to include a test to check not allow `domain` or `device token` as `null` on create a new _push contact_
> [no task] Add not allow domain or device token null on create push contact

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Models/Message.cs
Related to [DOM-129](https://makingsense.atlassian.net/browse/DOM-129)
> [DOM-129] Create send message to specific domain contract

- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/Messages/MessageSenderExtensions.cs
- Doppler.PushContact/Startup.cs
- Doppler.PushContact/appsettings.json
Este PR podría haber sido parte de https://github.com/FromDoppler/doppler-push-contact/pull/48 ya que aquí hago efectivo el envío. 
Pendiente:
Related to [DOM-138](https://makingsense.atlassian.net/browse/DOM-138)
> [DOM-138] Send message to target devices

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
Related to following use case section:
Related to [DOM-136](https://makingsense.atlassian.net/browse/DOM-136)
>  [DOM-136] Delete push contacts with not valid devices

- Doppler.PushContact/Services/Messages/MessageSender.cs
A little but **very important** bug fix
> [no-task] Valid target device calculation fix

- Doppler.PushContact/Startup.cs
This PR is to add CORS policy settings to allow requests from customers' hosts.
> [no-task] Add CORS policy settings

- api-contracts.http
> Fix documentation typo error

- Doppler.PushContact.Test/Controllers/DomainControllerTest.cs
- Doppler.PushContact.Test/Services/DomainServiceTest.cs
- Doppler.PushContact/Controllers/DomainController.cs
- Doppler.PushContact/Services/DomainService.cs
- Doppler.PushContact/Services/IDomainService.cs
This PR includes the following implementation:
Pendings:
Related to https://makingsense.atlassian.net/browse/DOM-277
> [DOM-277] Get Domain push feature status endpoint implementation

- Doppler.PushContact/Services/PushContactService.cs
I applied partially the `.editorconfig` from the following PR: 
https://github.com/FromDoppler/doppler-html-editor-api/pull/94
I found an important style violation
> Fix general styles conventions

- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Models/PushContactHistoryEvent.cs
- Doppler.PushContact/Services/PushContactDocumentProps.cs
- Doppler.PushContact/Services/PushContactService.cs
In this PR we store the related sent message ID. It will use to get sent message information.
Related to https://makingsense.atlassian.net/browse/DOM-323
> [DOM-323] Store sent message related ID

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/Messages/IMessageRepository.cs
- Doppler.PushContact/Services/Messages/MessageDetails.cs
- Doppler.PushContact/Services/Messages/MessageDocumentProps.cs
- Doppler.PushContact/Services/Messages/MessageRepository.cs
- Doppler.PushContact/Services/PushMongoContextExtensions.cs
- Doppler.PushContact/Services/PushMongoContextSettings.cs
- Doppler.PushContact/Services/PushServicesExtensions.cs
- Doppler.PushContact/Startup.cs
- Doppler.PushContact/appsettings.json
- README.md
In my opinion, It is a better alternative to https://github.com/FromDoppler/doppler-push-contact/pull/121
PR illustration
Related to https://makingsense.atlassian.net/browse/DOM-325
> [New approach][DOM-325] Get detailed message result

- README.md
A MongoDB ER diagram has been added
> docs: add mongodb ER diagram

- Doppler.PushContact/Services/PushContactService.cs
> Minor code format fix

- Doppler.PushContact/ApiModels/ApiPage.cs
- Doppler.PushContact/ApiModels/MessageDeliveryResult.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- An api contract for messages endpoint was defined
- ApiModels folder was created
- Message model was created, it will be the return of the endpoint "push-contact/messages"
> [DOM-375] - Define api contract for messages endpoint 

- Doppler.PushContact/ApiModels/DomainInfo.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- An api contract for domains endpoint was defined
- Domain model was created
> [DOM-379] - Define api contract for domains endpoint

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/IPushContactService.cs
- Doppler.PushContact/Services/PushContactService.cs
- Domains endpoint was implemented
- Tests were implemented
- [Task DOM-380](https://makingsense.atlassian.net/jira/software/projects/DOM/boards/84?selectedIssue=DOM-380)
- https://github.com/FromDoppler/doppler-push-contact/pull/149
> [DOM-380] - Implement domains endpoint

- Doppler.PushContact/Models/PushContactModel.cs
- Doppler.PushContact/Services/PushContactDocumentProps.cs
- Doppler.PushContact/Services/PushContactService.cs
- Now we have visitorGuid to link push contacts with datahub
Jira task: [DOP-1143](https://makingsense.atlassian.net/browse/DOP-1143)
> [DOP-1143] - Add visitorGuid

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/IPushContactService.cs
- Doppler.PushContact/Services/PushContactService.cs
- Now we can send push notifications by visitorGuid
- Jira ticket: [DOP-1144](https://makingsense.atlassian.net/browse/DOP-1144)
- Related pr: #177
> [DOP-1144] - Send push notification by visitor guid

- Doppler.PushContact.Test/Services/Messages/MessageSenderTest.cs
- Doppler.PushContact/Services/Messages/MessageSender.cs
- Doppler.PushContact/Services/Messages/MessageSenderSettings.cs
- Doppler.PushContact/appsettings.json
- Now we can send a push with more than 500 users sending them fractionally
> [DOP-1162] - Add limit sending push per push contacts quantity

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/IPushContactService.cs
- Doppler.PushContact/Services/PushContactService.cs
- Now we can get all the VisitorGuid by domain
- Jira task: [DOP-1145](https://makingsense.atlassian.net/browse/DOP-1145)
- #177 
- #178
> [DOP-1145] - Get all VisitorGuid by domain

- Doppler.PushContact/Services/Messages/IMessageRepository.cs
- Doppler.PushContact/Services/Messages/MessageRepository.cs
- Now we can get message details searching only by messageId
> [DOP-1172] - add GetMessageDetailsByMessageIdAsync

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/IPushContactService.cs
- Doppler.PushContact/Services/PushContactService.cs
- Now we have UpdatePushContactsAsync method to avoid repeat code
> [DOP-1186] - Refactorize send push

- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/IPushContactService.cs
- Doppler.PushContact/Services/PushContactService.cs
- Now we can filter by date in GetMessageDetails edpoint
Jira task: [DOP-1215](https://makingsense.atlassian.net/browse/DOP-1215)
> [DOP-1215] - Add filter by date in GetMessageDetails controller

- Doppler.PushContact/Services/PushContactService.cs
- Fixed a bug when the user request details in a date range that the message didn't had sent
> [NO-TICKET] - Fix get message results

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/Messages/IMessageRepository.cs
- Doppler.PushContact/Services/Messages/IMessageSender.cs
- Doppler.PushContact/Services/Messages/MessageRepository.cs
- Doppler.PushContact/Services/Messages/MessageSender.cs
- Doppler.PushContact/Services/Queue/BackgroundQueue.cs
- Doppler.PushContact/Services/Queue/IBackgroundQueue.cs
- Doppler.PushContact/Services/QueueBackgroundService.cs
- Doppler.PushContact/Startup.cs
New background service to allow send message to a domain in background
- Add repository method
- Add Background Service
- Add Concurrent Queue functionality
> Send messages in background

- Doppler.PushContact/Controllers/PushContactController.cs
Avoid breaks on background service that make crash the API, by checking device token list not empty and catching exceptions
> fix: catch exceptions on background methods

- Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
- Doppler.PushContact.Test/Services/PushContactServiceTest.cs
- Doppler.PushContact/Controllers/PushContactController.cs
- Doppler.PushContact/Services/IPushContactService.cs
- Doppler.PushContact/Services/PushContactService.cs
Add endpoint to update the `subscription`, for a push-contact, by `deviceToken`.
> Dop 1555 update subscription

- Doppler.PushContact.WebPushSender/Doppler.PushContact.WebPushSender.csproj
- Doppler.PushContact.WebPushSender/Program.cs
- Doppler.PushContact.WebPushSender/Repositories/Interfaces/IWebPushEventRepository.cs
- Doppler.PushContact.WebPushSender/Repositories/Models/WebPushEvent.cs
- Doppler.PushContact.WebPushSender/Repositories/Setup/RepositoryServiceExtensions.cs
- Doppler.PushContact.WebPushSender/Repositories/Setup/RepositorySettings.cs
- Doppler.PushContact.WebPushSender/Repositories/WebPushEventRepository.cs
- Doppler.PushContact.WebPushSender/appsettings.Development.json
- Doppler.PushContact.WebPushSender/appsettings.json
- backing-services-stack.yml
Missing: 
- consider add PushContactId and MessageId into WebPushEvent
- move some elements into appsettings.json file
**UPDATE**: `PushContactId` and `MessageId` were added into `WebPushEvent`
> Dop 1566 add repositories structure

- Doppler.PushContact.WebPushSender/Dockerfile
add the referenced projects to build image
> chore: include Models project in the Dockerfile

- Doppler.PushContact.Transversal.Test/Doppler.PushContact.Transversal.Test.csproj
- Doppler.PushContact.Transversal.Test/EncryptionHelperTest.cs
- Doppler.PushContact.Transversal/Doppler.PushContact.Transversal.csproj
- Doppler.PushContact.Transversal/EncryptionHelper.cs
- Doppler.PushContact.Transversal/EncryptionSettings.cs
- Doppler.PushContact.sln
Add `Doppler.PushContact.Tranversal` project, with `EncryptionHelper` utility; and also add `Doppler.PushContact.Tranversal.Test` project.
> Dop 1598 add transversal project with common functionality

- Doppler.PushContact/Repositories/WebPushEventRepository.cs
consider "ProcessingFailed" and "DeliveryFailedButRetry" types for "NotDelivered" summarization.
> fix: apply a little change into message report

- Doppler.PushContact.WebPushSender.Test/Senders/WebPushSenderBaseTest.cs
- Doppler.PushContact.WebPushSender/Senders/WebPushSenderBase.cs
> refactor: add improvement logging web push

- Doppler.PushContact.Models/DTOs/ContactsStatsDTO.cs
- Doppler.PushContact.Models/Models/DomainStats.cs
- Doppler.PushContact.Test/Controllers/DomainControllerTest.cs
- Doppler.PushContact.Test/Repositories/PushContactRepositoryTest.cs
- Doppler.PushContact.Test/Services/DomainServiceTest.cs
- Doppler.PushContact/Controllers/DomainController.cs
- Doppler.PushContact/Repositories/Interfaces/IPushContactRepository.cs
- Doppler.PushContact/Repositories/PushContactRepository.cs
- Doppler.PushContact/Services/DomainService.cs
- Doppler.PushContact/Services/IDomainService.cs
Se agrego endpoint para obtener las estadisticas de un dominio: `domains/{name}/stats`.
Response:
```
{
"name": "leoslopez.site",
"contactsStats": {
"deleted": 13,
"active": 7,
"total": 20
}
}
```
> Dop 1861 obtain contacts quantity by domain

- Doppler.PushContact.Test/Controllers/DomainControllerTest.cs
- Doppler.PushContact/Controllers/DomainController.cs
Return `NotFound` when domain does not exists.
> Dop 1861 consider domain notfound
