Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs
PR to include a test to check that `domain` parameter is present on GET method querystring.
=> [no-task] Add domain parameter on GET method required test

Doppler.PushContact.Test/Services/PushContactServiceTest.cs, Doppler.PushContact/Controllers/PushContactController.cs, Doppler.PushContact/Services/PushContactFilter.cs, Doppler.PushContact/Services/PushContactService.cs
Related to [DOM-109](https://makingsense.atlassian.net/browse/DOM-109)
This PR is to include filter by _push contact_ modified date. I will filter that modified date is between `from` and `to` query string params.
Following iterations:
- Sort element by modified date
- Include pagination (maybe _continuation token_)
- Prevent processing the same event (see [this](https://github.com/FromDoppler/doppler-push-contact/pull/25#discussion_r702963979) comment)
=> [DOM-109] Add from/to modified date filter on GET endpoint

Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs, Doppler.PushContact/Controllers/PushContactController.cs
To use add/update push contacts endpoints from user client we removed authorization in this PR.
**_Important: This PR does not be merged before include device token verification [(DOM-124)](https://makingsense.atlassian.net/browse/DOM-124)._**
Related to [DOM-123](https://makingsense.atlassian.net/browse/DOM-123)
=> [DOM-123] Allows anonymous on add/update push contacts endpoints

Doppler.PushContact.Test/Services/Messages/MessageSenderTest.cs, Doppler.PushContact/Services/Messages/ExternalContracts/SendMessageResponse.cs, Doppler.PushContact/Services/Messages/ExternalContracts/SendMessageResponseDetail.cs, Doppler.PushContact/Services/Messages/ExternalContracts/SendMessageResponseException.cs, Doppler.PushContact/Services/Messages/IMessageSender.cs, Doppler.PushContact/Services/Messages/IPushApiTokenGetter.cs, Doppler.PushContact/Services/Messages/MessageSender.cs, Doppler.PushContact/Services/Messages/MessageSenderSettings.cs, Doppler.PushContact/Services/Messages/PushApiTokenGetter.cs, Doppler.PushContact/Services/Messages/SendMessageResult.cs, Doppler.PushContact/Services/Messages/SendMessageTargetResult.cs
This PR contains the implementation of the [PushApi](https://github.com/FromDoppler/doppler-push-api) call to send push notifications. This will be used in the following use case:
Related to [DOM-131](https://makingsense.atlassian.net/browse/DOM-131).
=> [DOM-131] Message sender implementation (calling PushApi)

Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs, Doppler.PushContact/Controllers/PushContactController.cs, Doppler.PushContact/Models/MessageResult.cs
After make all send message steps asynchronous We will to response a `202-accepted` status code instead.
Related to [DOM-140](https://makingsense.atlassian.net/browse/DOM-140)
=> [DOM-140] Response 200 status code with a message id in send message endpoint

Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs, Doppler.PushContact.Test/Controllers/PushContactHistoryEventControllerTest.cs, Doppler.PushContact/Controllers/PushContactController.cs, Doppler.PushContact/Controllers/PushContactHistoryEventController.cs
The deleted endpoints were being called only from _Push Api_. I removed these calls in [this](https://github.com/FromDoppler/doppler-push-api/pull/40) PR.
Related to [DOM-141](https://makingsense.atlassian.net/browse/DOM-141)
=> [DOM-141] Remove obsolete endpoints

Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs, Doppler.PushContact.Test/Services/Messages/MessageSenderTest.cs, Doppler.PushContact/Controllers/PushContactController.cs, Doppler.PushContact/Models/Message.cs, Doppler.PushContact/Services/Messages/IMessageSender.cs, Doppler.PushContact/Services/Messages/MessageSender.cs, api-contracts.http
This PR allows sending an extra param named _OnClickLink_ in `POST /push-contacts/{domain}/message` method. 
The new _OnClickLink_ param is used to set a link to open when the final user clicks on the Push Notification:
https://user-images.githubusercontent.com/75738115/144899098-76654003-9d18-4ee9-b219-aac493ed40b8.mp4
**In the demonstration, I used _Android_ as OS, _Google Chrome_ as browser, and `https://app.fromdoppler.com/` as _OnClickLink_.**
Related to [DOM-186](https://makingsense.atlassian.net/browse/DOM-186) and https://github.com/FromDoppler/doppler-push-api/pull/54
=> [DOM-186] Add optional on click link in push message

Doppler.PushContact.Test/Services/PushContactServiceTest.cs, Doppler.PushContact/Services/PushContactService.cs, Doppler.PushContact/Services/PushContactServiceExtensions.cs, Doppler.PushContact/Services/PushMongoContextSettings.cs, Doppler.PushContact/appsettings.json
This refactor is to rename all MongoDB context-related _names_
Related to [DOM-270](https://makingsense.atlassian.net/browse/DOM-270) and https://github.com/MakingSense/doppler-swarm/pull/636
=> [DOM-270] Rename MongoDB context settings to use a generic name

Doppler.PushContact/Controllers/DomainController.cs
With the same request: 
`GET https://apisint.fromdoppler.net/doppler-push-contact/domains/pushint.fromdoppler.net/isPushFeatureEnabled`
**Response without `Cache-Control` header**
**Response with `Cache-Control` header**
=> Add response cache Headers

Doppler.PushContact/Services/PushMongoContextExtensions.cs, Doppler.PushContact/Services/PushMongoContextSettings.cs, Doppler.PushContact/appsettings.json
We had the connection string hardcoded in PushMongoExtensions.cs, that was a problem because we couldn't add extra parameters without changing the code.
With the new changes we have the connection string in the appsettings.json, this allows to add extra parameters without changing the code. Also we used MongoClientSettings to create the url and now i change it to MongoUrlBuilder.
I removed Username and Host from the appsetting because are not necessary any more.
I had to change appsettings file, so i had to change doppler-swarm too, these changes are in the next pr.
Related PR: https://github.com/MakingSense/doppler-swarm/pull/664
=> [DOM-87] - Allow extra parameters in connection string

Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs, Doppler.PushContact.Test/Services/PushContactServiceTest.cs, Doppler.PushContact/Controllers/PushContactController.cs, Doppler.PushContact/Services/IPushContactService.cs, Doppler.PushContact/Services/PushContactService.cs
- Now we can update all the old push contacts adding visitor_guid  if they have the deleted flag in false
- Jira task: [DOP-1159](https://makingsense.atlassian.net/browse/DOP-1159)
- #177 
- #178 
- #181
=> [DOP-1159] - Update old push contacts

Doppler.PushContact.Test/Controllers/DomainControllerTest.cs, Doppler.PushContact/Controllers/DomainController.cs, Doppler.PushContact/Services/Messages/IMessageSender.cs, Doppler.PushContact/Services/Messages/MessageSender.cs
Add a new enpoint to create a message (and return the related messageId) => (**POST**) `/domains/{domain}/message`.
Treat errors related to the body content and return a "proper" _http status code_ and a related message:
@mmosquera and @Manu0912 what do you think about this error code: **[422 Unprocessable Entity](https://www.rfc-editor.org/rfc/rfc4918#section-11.2)**
(Maybe we can consider treat in similar way those errors when send a message by token or visitorguid).
=> Dop 1171 add endpoint to create a new message

Doppler.PushContact.Test/Controllers/MessageControllerTest.cs, Doppler.PushContact/Controllers/MessageController.cs
- Now we can send specific message created previously to devices associated with a specific visitor guid 
- MessageController.cs was created
- MessageControllerTest.cs was created
- [DOP-1172](https://makingsense.atlassian.net/browse/DOP-1172)
- #189
=> [DOP-1172] - Send specific message to visitor guid

Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs, Doppler.PushContact.Test/Services/PushContactServiceTest.cs, Doppler.PushContact/Controllers/PushContactController.cs, Doppler.PushContact/Services/IPushContactService.cs, Doppler.PushContact/Services/PushContactService.cs
- Now we have an endpoint to know if a visitor guid has an active push contact
Ticket: [DOP-1314](https://makingsense.atlassian.net/jira/software/projects/DOP/boards/14?selectedIssue=DOP-1314)
[DOP-1314]: https://makingsense.atlassian.net/browse/DOP-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOP-1314] - Add endpoint to get push contact enabled by visitorGuid

Doppler.PushContact/Controllers/PushContactController.cs, Doppler.PushContact/Services/Messages/MessageRepository.cs
Se mejoró el endpoint para obtener las estadisticas de un mensaje, para los reportes. 
Ahora los numeros se obtienen directamente desde el mensaje, si el mismo los tiene registrados, sino se seguirá sumarizando los `history_events` de `push_contacts`, como se hace actualmente.
=> Dop 1522 improve getting message results

Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs, Doppler.PushContact.Test/Services/PushContactServiceTest.cs, Doppler.PushContact/Controllers/MessageController.cs, Doppler.PushContact/Controllers/PushContactController.cs, Doppler.PushContact/Services/IPushContactService.cs, Doppler.PushContact/Services/Messages/IMessageRepository.cs, Doppler.PushContact/Services/Messages/MessageRepository.cs, Doppler.PushContact/Services/PushContactService.cs
Se modificó el endpoint para envio de un mensaje existente, para que incremente las estadisticas de envio en el mensaje apropiadamente.
Ademas se refactorizo el endpoint para envio de un mensaje nuevo. Se reemplazo el comportamiento definido en el controller por el uso del metodo `AddHistoryEventsAsync` (antes llamado `UpdatePushContactsAsync`) definido en el `PushContactService`.
=> Dop 1529 increment message stats sending an existent message

Doppler.PushContact.QueuingService/Doppler.PushContact.QueuingService.csproj, Doppler.PushContact.QueuingService/MessageQueueBroker/IMessageQueuePublisher.cs, Doppler.PushContact.QueuingService/MessageQueueBroker/IMessageQueueSubscriber.cs, Doppler.PushContact.QueuingService/MessageQueueBroker/MessageQueueBrokerSettings.cs, Doppler.PushContact.QueuingService/MessageQueueBroker/RabbitMessageQueuePublisher.cs, Doppler.PushContact.QueuingService/MessageQueueBroker/RabbitMessageQueueSubscriber.cs, Doppler.PushContact.sln
A project to handle publishing and subscribing to Rabbit queues was added.
According to reading about [Exchange Topics](https://www.rabbitmq.com/tutorials/tutorial-five-python), the Exchange type used for now is Default (`Exchange.Default`), because the `Topic` is not working as we imagined; using the `Topic` does not guarantee handling only one queue, quite the opposite.
=> Dop 1579 add push contact queuingservice project

Doppler.PushContact.QueuingService/MessageQueueBroker/MessageQueueBrokerExtensions.cs, Doppler.PushContact.Test/Controllers/MessageControllerTest.cs, Doppler.PushContact.Test/Services/Messages/MessageSenderTest.cs, Doppler.PushContact.Test/Services/PushContactServiceTest.cs, Doppler.PushContact.Test/Services/WebPushPublisherServiceTest.cs, Doppler.PushContact.sln, Doppler.PushContact/Controllers/MessageController.cs, Doppler.PushContact/DTOs/DopplerWebPushDTO.cs, Doppler.PushContact/DTOs/SubscriptionInfoDTO.cs, Doppler.PushContact/DTOs/WebPushDTO.cs, Doppler.PushContact/Doppler.PushContact.csproj, Doppler.PushContact/Services/IPushContactService.cs, Doppler.PushContact/Services/IWebPushPublisherService.cs, Doppler.PushContact/Services/Messages/IMessageSender.cs, Doppler.PushContact/Services/Messages/MessageSender.cs, Doppler.PushContact/Services/PushContactService.cs, Doppler.PushContact/Services/PushServicesExtensions.cs, Doppler.PushContact/Services/WebPushPublisherService.cs, Doppler.PushContact/Services/WebPushQueueSettings.cs, Doppler.PushContact/Startup.cs, Doppler.PushContact/appsettings.Development.json, Doppler.PushContact/appsettings.json, README.md, backing-services-stack.yml
A new endpoint to enqueue firebase notifications by domain was added: `message/domains/{domain}`.
When this endpoint is called, all device tokens for this domain, obtained from the DB, will be enqueued to send the proper notifications.
**Note**: review commit by commit to understanding changes in a better way.
**UPDATE!!!** the changes discussed with @mmosquera have been added. When it is identified that the contact has a `subscription` (to be used sending with Doppler), the message to be sent is enqueued. If there is no `subscription` but there is a **Firebase** `deviceToken`, the message will be sent immediately using **Firebase**."
An example enqueueing messages in the local environment:
=> Dop 1579 publish notification in queues

Doppler.PushContact.QueuingService/MessageQueueBroker/MessageQueueBrokerExtensions.cs, Doppler.PushContact.WebPushSender/DTOs/DopplerWebPushDTO.cs, Doppler.PushContact.WebPushSender/DTOs/SubscriptionDTO.cs, Doppler.PushContact.WebPushSender/DTOs/WebPushApi/SendMessageResponse.cs, Doppler.PushContact.WebPushSender/DTOs/WebPushApi/SendMessageResponseDetail.cs, Doppler.PushContact.WebPushSender/DTOs/WebPushApi/SendMessageResponseException.cs, Doppler.PushContact.WebPushSender/DTOs/WebPushApi/SubscriptionResponse.cs, Doppler.PushContact.WebPushSender/DTOs/WebPushDTO.cs, Doppler.PushContact.WebPushSender/DTOs/WebPushProcessingResult.cs, Doppler.PushContact.WebPushSender/Doppler.PushContact.WebPushSender.csproj, Doppler.PushContact.WebPushSender/Logging/LogglySetup.cs, Doppler.PushContact.WebPushSender/Logging/SerilogSetup.cs, Doppler.PushContact.WebPushSender/Program.cs, Doppler.PushContact.WebPushSender/SenderExecutor.cs, Doppler.PushContact.WebPushSender/Senders/DefaultWebPushSender.cs, Doppler.PushContact.WebPushSender/Senders/IWebPushSender.cs, Doppler.PushContact.WebPushSender/Senders/IWebPushSenderFactory.cs, Doppler.PushContact.WebPushSender/Senders/WebPushSenderBase.cs, Doppler.PushContact.WebPushSender/Senders/WebPushSenderFactory.cs, Doppler.PushContact.WebPushSender/Senders/WebPushSenderSettings.cs, Doppler.PushContact.WebPushSender/Senders/WebPushSenderTypes.cs, Doppler.PushContact.WebPushSender/appsettings.Development.json, Doppler.PushContact.WebPushSender/appsettings.json, Doppler.PushContact.sln
Add a new project to implement a background service that creates a `WebPushSender` according to a specific configuration.  This sender subscribes to a Rabbit queue (according to a configuration too) and sends a web push using the Doppler Push API.
**TODO**:
- analyze options to handle (or remove) push API token
- analyze delivery results and take proper actions (register in db, retry, etc)
- add unit tests
**IMPORTANT**: review it commit by commit to understanding better.
=> Dop 1579 add queues consumer

Doppler.PushContact.Models/DTOs/DopplerWebPushDTO.cs, Doppler.PushContact.Test/Services/WebPushPublisherServiceTest.cs, Doppler.PushContact.WebPushSender/Senders/WebPushSenderBase.cs, Doppler.PushContact/Doppler.PushContact.csproj, Doppler.PushContact/Services/PushServicesExtensions.cs, Doppler.PushContact/Services/WebPushPublisherService.cs, Doppler.PushContact/Services/WebPushPublisherSettings.cs, Doppler.PushContact/Services/WebPushQueueSettings.cs, Doppler.PushContact/Startup.cs, Doppler.PushContact/appsettings.json
Add support to register clicked and received events when enqueueing messages, and sending webpush.
**Missing:** add new endpoints to process and register both events
=> Dop 1598 add clicked n received events support to enqueue n send webpush

Doppler.PushContact.Test/Services/PushContactServiceTest.cs, Doppler.PushContact/Services/PushContactService.cs
When it tries to add a contact with a duplicated `deviceToken`, the service will treat it as successful insert.
=> Dop 1602 fix treatment when try to insert duplicated pushcontact

Doppler.PushContact/Controllers/DomainController.cs, Doppler.PushContact/Models/Domain.cs, Doppler.PushContact/Services/DomainDocumentProps.cs, Doppler.PushContact/Services/DomainService.cs
Register `UsesExternalPushDomain` (flag to indicate if external push is available) and `ExternalPushDomain` (the external domain to implement push notification).
=> feat: modify endpoint to insert/update domains

Doppler.PushContact.Test/Controllers/MessageControllerTest.cs, Doppler.PushContact.Test/Doppler.PushContact.Test.csproj, Doppler.PushContact.Test/Repositories/PushContactRepositoryTest.cs, Doppler.PushContact.Test/Services/WebPushPublisherServiceTest.cs, Doppler.PushContact/Controllers/MessageController.cs, Doppler.PushContact/Properties/AssemblyInfo.cs, Doppler.PushContact/Repositories/Interfaces/IPushContactRepository.cs, Doppler.PushContact/Repositories/PushContactRepository.cs, Doppler.PushContact/Services/IWebPushPublisherService.cs, Doppler.PushContact/Services/PushMongoContextExtensions.cs, Doppler.PushContact/Services/PushMongoContextSettings.cs, Doppler.PushContact/Services/WebPushPublisherService.cs, Doppler.PushContact/Services/WebPushPublisherSettings.cs, Doppler.PushContact/appsettings.json
Mejorar la performance en la obtencion de los contactos al momento de enviar push:
- se agregó nuevo indice en `push-contacts`: `{ domain: 1, deleted: 1 }`
- se agregó un metodo para obtener la informacion de los contactos de la base usando cursor: `GetSubscriptionInfoByDomainAsStreamAsync `
- se agregó un metodo para procesar los envios de push por batches (por subscripcion y/o device token): `ProcessWebPushInBatches`
=> Dop 1851 improve performance getting contacts

Doppler.PushContact.Test/Services/Messages/MessageRepositoryTest.cs, Doppler.PushContact/Services/Messages/MessageRepository.cs
Fix del update de los contadores en la collection de `messages`.
Antes del **tratamiento por batches**, se hacia el envio de un mensaje a todos los `push-contacts`, y luego se actualizaban de una los contadores de `messages`. Ahora, al **procesar por batches**, debe ir **incrementandose esos valores** cuando se procesa cada **batch de tokens**.
=> Dop 1851 fix message counters summarization

Doppler.PushContact.Models/DTOs/DomainDTO.cs, Doppler.PushContact.Test/Controllers/DomainControllerTest.cs, Doppler.PushContact.Test/Controllers/PushContactControllerTest.cs, Doppler.PushContact.Test/Repositories/DomainRepositoryTest.cs, Doppler.PushContact/Controllers/DomainController.cs, Doppler.PushContact/Repositories/DomainRepository.cs, Doppler.PushContact/Repositories/Interfaces/IDomainRepository.cs, Doppler.PushContact/Services/DomainService.cs, Doppler.PushContact/Services/IDomainService.cs, Doppler.PushContact/Startup.cs
Se agregó el `DomainRepository`, y se movió el **acceso a la base de datos** que se hacía desde `DomainService`.
El `DomainService` quedó, por el momento, como un simple pasa-manos del **Controller** al **Repository**.
El siguiente paso es poder utilizar la nueva estructura para **obtener la cantidad de contactos que tiene un dominio dado**.
=> Dop 1861 add domain repository and use instead domain service

Doppler.PushContact.Test/Repositories/PushContactRepositoryTest.cs, Doppler.PushContact.Test/Services/WebPushPublisherServiceTest.cs, Doppler.PushContact/Repositories/Interfaces/IPushContactRepository.cs, Doppler.PushContact/Repositories/PushContactRepository.cs, Doppler.PushContact/Services/PushMongoContextExtensions.cs, Doppler.PushContact/Services/WebPushPublisherService.cs
Considerar el dominio al que pertenece el mensaje al momento de obtener las subscripciones para un contacto con un determinado `visitor_guid`. Si el **dominio del `message`** no coincide con el **dominio del `push-contact`** la subscripcion no sera considerada para hacer el envio.
=> No ticket consider domain sending by visitorguid
